# Generated by Django 3.0.9 on 2020-08-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=0.123),
            preserve_default=False,
        ),
    ]
